# Copyright 2025 wxvirus(无解的游戏). All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/sword-demon/go18. The professional
# version of this repository is https://github.com/sword-demon/go18.

app:
  host: 127.0.0.1
  port: 8080
mysql:
  host: 127.0.0.1
  port: 3306
  database: test
  username: "root"
  password: "admin888"
  debug: true