# 所有的配置

[app]
name = "devcloud"
description = "app desc"
address = "http://127.0.0.1:8080"
ecrypt_key = "wujiedeyouxi"

[datasource]
provider = "mysql"
host = "127.0.0.1"
port = 3306
database = "devcloud_go18"
username = "root"
password = "admin888"
auto_migrate = true
debug = false

[mongo]
endpoints = ["127.0.0.1:27017"]
username = "admin"
password = "secret"
database = "devcloud_go18"
# auth_db = "admin"
# trace = true

[kafka]
brokers = ["127.0.0.1:9092"]
scram_algorithm = "SHA512"
username = ""
password = ""
# debug = false

[http]
host = "127.0.0.1"
port = 8080
path_prefix = "api"